### ISSUE TITLE
getAllBlobPaths does not paginate

### ISSUE THREAD

**Issue by jasoncwik** [EMCECS/ecs-zimbra-store-manager#1]
The code in getAllBlobPaths does not check for isTruncated and iterate.  Therefore, it will only return 1000 results maximum.  Need to add check for isTruncated.

https://github.com/EMCECS/ecs-zimbra-store-manager/blob/master/src/main/java/com/emc/ecs/zimbra/integration/EcsStoreManager.java#L187

**Comment by DavidASeibert** [comment]
Done.
