### ISSUE TITLE
Avoid using TransferManager for small objects

### ISSUE THREAD

**Issue by jasoncwik** [EMCECS/ecs-zimbra-store-manager#2]
Currently, all of the code is using TransferManager.  While this is good for large uploads, using default constructor will create a thread pool with only 10 threads and all requests will be throttled through there.

Since ECS can naturally support a very high concurrency, we should ensure that we do not throttle requests through a fixed thread pool.  This means we should only use TransferManager for large objects and do regular putObject calls for small objects.

**Comment by DavidASeibert** [comment]
Done. All Zimbra data transfer is done via streams, so everything goes through the standard object upload channel, not the LargeFileUploader.
