### ISSUE TITLE
Include Zimbra compile dependency

### ISSUE THREAD

**Issue by jasoncwik** [EMCECS/ecs-zimbra-store-manager#5]
The Zimbra dependency required to compile the code is not included in Maven Central or any other artifact repository I know of.  The dependency includes the interfaces required to compile the connector.  We should include the dependency in the code so we can compile against it.

Also, the current Maven build is referencing 9.0.  We can build against 8.6; the interface hasn't changed and 9.0 hasn't been released for the community edition yet.

**Comment by DavidASeibert** [comment]
Done for 8.6 and 8.7. 9.0 is not available yet.
